remote_theme: pmarsceill/just-the-docs


# TODO change these 4
title: Course Name 
description: Course description 

baseurl: coursesetup # repo name
url: "https://iarigby.github.io" 



exclude: [] 

search_enabled: true
search:
  heading_level: 4
  previews: 3 # TODO what does this do
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false # TODO try changing

heading_anchors: true


# TODO change
aux_links: 
    "See the subject code on GitHub":
    - "//github.com/iarigby/coursesetup"
    "Join google classroom":
    - "//classroom.google.com"

aux_links_new_tab: true

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
# TODO change this
gh_edit_repository: "https://github.com/iarigby/coursesetup" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


color_scheme: nil

# TODO add more plugins
plugins:
  - jekyll-seo-tag

# TODO what does this do
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false